connection_url: 'mongodb://pigpig:0iEF&C84k4gqe&d&2D38%5EtNb&xln6d03hXLOGAcbY0LeRGUlGj@192.168.100.10:27017/'
db_name: 'prototipoGranjaCancun'
db_nameChilac: 'prototipoGranjaChilac'
db_cerdos: 'cerdos'
db_simulacion: 'simulacion'
db_historial: 'historial'

registroPartos: 'Generales/RegistroPartos.yaml'

archivo_config_inicial: 'configuracionInicial.yaml'

porcentajeMuerte: 15

